apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
      version: v2
  template:
    metadata:
      labels:
        app: sample-app
        version: v2
    spec:
      containers:
        - name: sample-app
          image: hashicorp/http-echo
          args:
            - "-text=v2"
          ports:
            - containerPort: 5678