apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: sample-app-vs
spec:
  hosts:
    - sample-app
  http:
    - route:
        - destination:
            host: sample-app
            subset: v1
          weight: 100
        - destination:
            host: sample-app
            subset: v2
          weight: 0
